version: 2.1

references:

  ## Workspace

  workspace: &workspace
               ~/workspace

executors:
  jdk_executor:
    working_directory: *workspace
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.caching=true

commands:
  restore_gradle_cache:
    steps:
      - restore_cache:
          keys:
            - v2-gradle_cache-{{ .Branch }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "buildSrc/src/main/kotlin/Libs.kt" }}-{{ checksum "buildSrc/src/main/kotlin/BuildLibs.kt" }}
            - v2-gradle_cache-{{ .Branch }}
            - v2-gradle_cache-

  save_gradle_cache:
    steps:
      - save_cache:
          key: v2-gradle_cache-{{ .Branch }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "buildSrc/src/main/kotlin/Libs.kt" }}-{{ checksum "buildSrc/src/main/kotlin/BuildLibs.kt" }}
          paths:
            - ~/.gradle
            - ~/.m2

  restore_gradle_build_cache:
    steps:
      - restore_cache:
          keys:
            - v1-gradle_build_cache-{{ .Revision }}-

  save_gradle_build_cache:
    steps:
      - save_cache:
          key: v1-gradle_build_cache-{{ .Revision }}-{{ epoch }}
          paths:
            - ~/.gradle-build-cache

  clean_build_cache:
    steps:
      - run:
          name: Clean Build Cache
          command: rm -rf ~/.gradle-build-cache

jobs:
  gradleCache:
    executor: jdk_executor
    steps:
      - checkout
      - clean_build_cache
      - restore_gradle_cache
      - run:
          name: Download dependencies
          command: ./gradlew dependencies --stacktrace
      - save_gradle_cache
      - save_gradle_build_cache


  ktlint:
    executor: jdk_executor
    steps:
      - checkout
      - restore_gradle_cache
      - run:
          name: Ktlint
          command: ./gradlew ktlint --stacktrace

  build:
    executor: jdk_executor
    steps:
      - checkout
      - restore_gradle_cache
      - restore_gradle_build_cache
      - run:
          name: Assemble
          command: ./gradlew assemble --stacktrace
      - save_gradle_build_cache
      - store_artifacts:
          path: ./build/libs
          destination: wars

  test:
    executor: jdk_executor
    steps:
      - checkout
      - restore_gradle_cache
      - restore_gradle_build_cache
      - run:
          name: Run tests
          command: ./gradlew test --stacktrace
      - run:
          name: Save test results 
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ./build/reports/tests/test
          destination: tests

  publish:
    executor: jdk_executor
    steps:
      - checkout
      - restore_gradle_cache
      - restore_gradle_build_cache
      - run:
          name: Uploading to Nexus Sonatype
          command: ./gradlew publish -PLOCAL_UPLOAD=false --refresh-dependencies --stacktrace

  upgradeDependencies:
    executor: jdk_executor
    steps:
      - checkout
      - restore_gradle_cache
      - run:
          name: Upgrade Dependencies
          command: ./gradlew upgradeDependencies -PpullRequestEnabled=true --stacktrace

workflows:
  commit:
    jobs:
      - gradleCache
      - ktlint
      - build:
          requires:
            - gradleCache
            - ktlint
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - upgradeDependencies
