version: 2.1

references:

  ## Workspace

  workspace: &workspace
               ~/workspace

executors:
  jdk_executor:
    working_directory: *workspace
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.caching=false

commands:
  restore_gradle_cache:
    steps:
      - restore_cache:
          keys:
            - v1-gradle_cache-{{ .Branch }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "buildSrc/src/main/kotlin/Libs.kt" }}-{{ checksum "buildSrc/src/main/kotlin/BuildLibs.kt" }}
            - v1-gradle_cache-{{ .Branch }}
            - v1-gradle_cache-

  save_gradle_cache:
    steps:
      - save_cache:
          key: v1-gradle_cache-{{ .Branch }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "buildSrc/src/main/kotlin/Libs.kt" }}-{{ checksum "buildSrc/src/main/kotlin/BuildLibs.kt" }}
          paths:
            - ~/.gradle
            - ~/.m2

jobs:
  gradleCache:
    executor: jdk_executor
    steps:
      - checkout

      - restore_gradle_cache
      - run:
          name: Download dependencies
          command: ./gradlew dependencies --refresh-dependencies --stacktrace
      - save_gradle_cache

  build:
    executor: jdk_executor
    steps:
      - checkout
      - restore_gradle_cache
      - run:
          name: Assemble
          command: ./gradlew assemble --stacktrace
      - store_artifacts:
          path: ./build/libs
          destination: wars

  ktlint:
    executor: jdk_executor
    steps:
      - checkout
      - restore_gradle_cache
      - run:
          name: Ktlint
          command: ./gradlew ktlint --stacktrace

  test:
    executor: jdk_executor
    steps:
      - checkout
      - restore_gradle_cache

      - run: ./gradlew test --stacktrace
      - run:
          name: Save test results 
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ./build/reports/tests/test
          destination: tests

  publish:
    executor: jdk_executor
    steps:
      - checkout
      - restore_gradle_cache
      - run:
          name: Uploading to Nexus Sonatype
          command: ./gradlew publish -PLOCAL_UPLOAD=false --refresh-dependencies --stacktrace

  upgradeDependencies:
    executor: jdk_executor
    steps:
      - checkout
      - restore_gradle_cache
      - run:
          name: Upgrade Dependencies
          command: ./gradlew upgradeDependencies -PpullRequestEnabled=true --stacktrace

workflows:
  commit:
    jobs:
      - ktlint
      - gradleCache
      - build:
          requires:
            - ktlint
            - gradleCache
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - upgradeDependencies
